/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.facebook.publishinstall;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.facebook.Settings;


@Kroll.module(name="Publishinstall", id="com.facebook.publishinstall")
public class PublishinstallModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "PublishinstallModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public PublishinstallModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "Facebook Publish Install Module created");
	}
	
	@Kroll.method
	public void publishInstall(String appId) {
		Settings.publishInstallAsync(TiApplication.getInstance(), appId);
	}	
}

